spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://locahost:3306/customer-service
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: flase
