global:
  message: welcome to customer service prod environment
server:
  port: 8083
message: hello from prod
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cust_pord
    username: root
    password: Karan@1709
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
