global:
  message: welcome to customer service dev environment
server:
  port: 8082
message: hello from dev
spring:
  datasource:
    url: jdbc:mysql://locahost:3306/cust_dev
    username: root
    password: Karan@1709
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
