global:
  message: welcome to order service dev environment
server:
  port: 8084
message: hello from order dev
spring:
  datasource:
    url: jdbc:mysql://locahost:3306/order_dev
    username: root
    password: Karan@1709
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  
